name: Actualizador Automatico de Canales
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta a medianoche
  workflow_dispatch: # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.11'

      - name: Instalar yt-dlp
        run: pip install yt-dlp

      - name: Ejecutar script de actualización
        run: python update_list.py

      - name: Guardar cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tvnicaragua.m3u8
          git commit -m "Canales actualizados: $(date)" || exit 0
          git push
